import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { type DeployTarget, applyDeployConfig } from './deploy.js';
import { log } from './logger.js';
import { STACK } from './stack.js';

export interface ScaffoldOptions {
  deployTarget?: DeployTarget;
}

export interface ScaffoldResult {
  ok: boolean;
  dir: string;
  error?: string;
  existingFiles?: string[];
}

export function scaffold(targetDir: string, opts: ScaffoldOptions = {}): ScaffoldResult {
  const dir = path.resolve(targetDir);

  if (fs.existsSync(dir)) {
    const entries = fs.readdirSync(dir);
    if (entries.length > 0) {
      return {
        ok: false,
        dir,
        error: `Directory ${dir} is not empty — refusing to scaffold.`,
        existingFiles: entries,
      };
    }
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }

  log.step(`Scaffolding Astro project at ${dir}`);

  writeFiles(dir);

  if (opts.deployTarget) {
    applyDeployConfig(dir, opts.deployTarget);
  }

  log.info('Running npm install (this can take a minute)…');
  const npm = spawnSync('npm', ['install', '--no-audit', '--no-fund'], {
    cwd: dir,
    stdio: 'inherit',
  });
  if (npm.status !== 0) {
    return { ok: false, dir, error: 'npm install failed. See output above.' };
  }

  log.info('Initialising git repo');
  const gitInit = spawnSync('git', ['init', '-q'], { cwd: dir, stdio: 'inherit' });
  if (gitInit.status === 0) {
    spawnSync('git', ['add', '.'], { cwd: dir, stdio: 'ignore' });
    spawnSync('git', ['commit', '-q', '-m', 'astro-mate: initial scaffold'], {
      cwd: dir,
      stdio: 'ignore',
    });
  }

  log.ok('Scaffold complete');
  return { ok: true, dir };
}

function writeFiles(dir: string): void {
  const files: Record<string, string> = {
    'package.json': packageJson(path.basename(dir)),
    'astro.config.mjs': astroConfig(),
    'tsconfig.json': tsconfig(),
    'biome.json': biomeConfig(),
    '.gitignore': gitignore(),
    'src/pages/index.astro': indexPage(),
    'src/layouts/Layout.astro': layout(),
    'src/styles/global.css': globalCss(),
    'public/favicon.svg': favicon(),
    'README.md': `# ${path.basename(dir)}\n\nGenerated by astro-mate. Stack: Astro ${STACK.astro}, Tailwind ${STACK.tailwind}, Biome, TypeScript strict.\n\n## Dev\n\n\`\`\`bash\nnpm run dev        # dev server\nnpm run build      # production build\nnpm run check      # astro check + biome check\n\`\`\`\n`,
  };

  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }
}

function packageJson(name: string): string {
  return `${JSON.stringify(
    {
      name,
      type: 'module',
      version: '0.0.1',
      private: true,
      scripts: {
        dev: 'astro dev',
        build: 'astro build',
        preview: 'astro preview',
        astro: 'astro',
        'astro:check': 'astro check',
        'biome:check': 'biome check src/',
        'biome:fix': 'biome check --write src/',
        check: 'astro check && biome check src/',
      },
      dependencies: {
        astro: STACK.astro,
        tailwindcss: STACK.tailwind,
        '@tailwindcss/vite': STACK.tailwind,
      },
      devDependencies: {
        '@astrojs/check': STACK.astroCheck,
        '@biomejs/biome': STACK.biome,
        typescript: STACK.typescript,
      },
    },
    null,
    2,
  )}\n`;
}

function astroConfig(): string {
  return `import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

export default defineConfig({
  vite: {
    plugins: [tailwindcss()],
  },
});
`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      extends: 'astro/tsconfigs/strict',
      include: ['.astro/types.d.ts', '**/*'],
      exclude: ['dist'],
      compilerOptions: {
        baseUrl: '.',
        paths: { '@/*': ['src/*'] },
      },
    },
    null,
    2,
  )}\n`;
}

function biomeConfig(): string {
  return `${JSON.stringify(
    {
      $schema: 'https://biomejs.dev/schemas/1.9.4/schema.json',
      vcs: { enabled: true, clientKind: 'git', useIgnoreFile: true },
      files: {
        ignoreUnknown: true,
        ignore: ['dist', '.astro', 'node_modules', '*.astro'],
      },
      formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineWidth: 100 },
      linter: { enabled: true, rules: { recommended: true } },
      javascript: { formatter: { quoteStyle: 'single', semicolons: 'always' } },
    },
    null,
    2,
  )}\n`;
}

function gitignore(): string {
  return `# build output
dist/
.astro/
/.cache/

# dependencies
node_modules/

# env files
.env
.env.local
.env.*.local
.env.production

# logs
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
yarn-error.log*

# astro-mate scratch (temp prompt file; stays if the runner is killed mid-run)
.astro-mate-prompt.md

# system
.DS_Store
`;
}

function layout(): string {
  return `---
import '../styles/global.css';

interface Props {
  title: string;
}

const { title } = Astro.props;
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <title>{title}</title>
  </head>
  <body class="min-h-screen bg-white text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
    <slot />
  </body>
</html>
`;
}

function indexPage(): string {
  return `---
import Layout from '../layouts/Layout.astro';
---

<Layout title="Hello from astro-mate">
  <main class="mx-auto max-w-2xl px-6 py-24">
    <h1 class="text-4xl font-bold tracking-tight">Hello from astro-mate</h1>
    <p class="mt-4 text-lg text-slate-600 dark:text-slate-400">
      Edit <code class="rounded bg-slate-100 px-1.5 py-0.5 text-sm dark:bg-slate-800">src/pages/index.astro</code>
      to begin.
    </p>
  </main>
</Layout>
`;
}

function globalCss(): string {
  return `@import "tailwindcss";
`;
}

function favicon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="24" fill="#0f172a"/><text x="64" y="82" text-anchor="middle" font-family="system-ui,sans-serif" font-size="64" font-weight="700" fill="#f8fafc">A</text></svg>
`;
}
