import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { applyDeployConfig, type DeployTarget } from './deploy.js';
import { log } from './logger.js';
import { STACK } from './stack.js';

export interface ScaffoldOptions {
  deployTarget?: DeployTarget;
  site?: string;
}

export interface ScaffoldResult {
  ok: boolean;
  dir: string;
  error?: string;
  existingFiles?: string[];
}

export function scaffold(targetDir: string, opts: ScaffoldOptions = {}): ScaffoldResult {
  const dir = path.resolve(targetDir);

  if (fs.existsSync(dir)) {
    const entries = fs.readdirSync(dir);
    if (entries.length > 0) {
      return {
        ok: false,
        dir,
        error: `Directory ${dir} is not empty — refusing to scaffold.`,
        existingFiles: entries,
      };
    }
  } else {
    fs.mkdirSync(dir, { recursive: true });
  }

  log.step(`Scaffolding Astro project at ${dir}`);

  writeFiles(dir, opts.site);

  if (opts.deployTarget) {
    applyDeployConfig(dir, opts.deployTarget);
  }

  log.info('Running npm install (this can take a minute)…');
  const npm = spawnSync('npm', ['install', '--no-audit', '--no-fund'], {
    cwd: dir,
    stdio: 'inherit',
  });
  if (npm.status !== 0) {
    return { ok: false, dir, error: 'npm install failed. See output above.' };
  }

  log.info('Initialising git repo');
  const gitInit = spawnSync('git', ['init', '-q'], { cwd: dir, stdio: 'inherit' });
  if (gitInit.status === 0) {
    spawnSync('git', ['add', '.'], { cwd: dir, stdio: 'ignore' });
    spawnSync('git', ['commit', '-q', '-m', 'astro-mate: initial scaffold'], {
      cwd: dir,
      stdio: 'ignore',
    });
  }

  log.ok('Scaffold complete');
  return { ok: true, dir };
}

function writeFiles(dir: string, site?: string): void {
  const resolvedSite = site?.trim() || 'https://example.com';
  const isPlaceholder = !site?.trim();

  const files: Record<string, string> = {
    'package.json': packageJson(path.basename(dir)),
    'astro.config.mjs': astroConfig(resolvedSite, isPlaceholder),
    'tsconfig.json': tsconfig(),
    'biome.json': biomeConfig(),
    '.prettierrc.json': prettierConfig(),
    '.prettierignore': prettierIgnore(),
    '.gitignore': gitignore(),
    'src/pages/index.astro': indexPage(),
    'src/layouts/Layout.astro': layout(),
    'src/components/SEO.astro': seoComponent(),
    'src/styles/global.css': globalCss(),
    'public/favicon.svg': favicon(),
    'public/robots.txt': robotsTxt(resolvedSite),
    'README.md': `# ${path.basename(dir)}\n\nGenerated by astro-mate. Stack: Astro ${STACK.astro}, Tailwind ${STACK.tailwind}, @astrojs/sitemap, Biome (\`.ts\`/\`.js\`/\`.json\`), Prettier + prettier-plugin-astro (\`.astro\`), TypeScript strict.\n\n## Dev\n\n\`\`\`bash\nnpm run dev        # dev server\nnpm run build      # production build\nnpm run check      # astro check + biome check + prettier check\n\`\`\`\n`,
  };

  for (const [rel, content] of Object.entries(files)) {
    const full = path.join(dir, rel);
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content, 'utf-8');
  }
}

function packageJson(name: string): string {
  return `${JSON.stringify(
    {
      name,
      type: 'module',
      version: '0.0.1',
      private: true,
      scripts: {
        dev: 'astro dev',
        build: 'astro build',
        preview: 'astro preview',
        astro: 'astro',
        'astro:check': 'astro check',
        'biome:check': 'biome check src/',
        'biome:fix': 'biome check --write src/',
        'prettier:check': 'prettier --check "**/*.astro"',
        'prettier:fix': 'prettier --write "**/*.astro"',
        check: 'astro check && biome check src/ && prettier --check "**/*.astro"',
      },
      dependencies: {
        astro: STACK.astro,
        tailwindcss: STACK.tailwind,
        '@tailwindcss/vite': STACK.tailwind,
        '@astrojs/sitemap': STACK.sitemap,
      },
      devDependencies: {
        '@astrojs/check': STACK.astroCheck,
        '@biomejs/biome': STACK.biome,
        prettier: STACK.prettier,
        'prettier-plugin-astro': STACK.prettierPluginAstro,
        typescript: STACK.typescript,
      },
    },
    null,
    2,
  )}\n`;
}

function astroConfig(site: string, isPlaceholder: boolean): string {
  const todo = isPlaceholder ? '  // TODO: set your production URL\n' : '';
  return `import { defineConfig, fontProviders } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';
import sitemap from '@astrojs/sitemap';

export default defineConfig({
${todo}  site: '${site}',
  integrations: [sitemap()],
  fonts: [
    {
      provider: fontProviders.google(),
      name: 'Inter',
      cssVariable: '--font-inter',
      weights: [400, 500, 600, 700],
    },
  ],
  vite: {
    plugins: [tailwindcss()],
  },
});
`;
}

function tsconfig(): string {
  return `${JSON.stringify(
    {
      extends: 'astro/tsconfigs/strict',
      include: ['.astro/types.d.ts', '**/*'],
      exclude: ['dist'],
      compilerOptions: {
        baseUrl: '.',
        paths: { '@/*': ['src/*'] },
      },
    },
    null,
    2,
  )}\n`;
}

function biomeConfig(): string {
  return `${JSON.stringify(
    {
      $schema: 'https://biomejs.dev/schemas/2.4.16/schema.json',
      vcs: { enabled: true, clientKind: 'git', useIgnoreFile: true },
      files: {
        ignoreUnknown: true,
        includes: ['**', '!**/dist', '!**/.astro', '!**/node_modules', '!**/*.astro'],
      },
      formatter: { enabled: true, indentStyle: 'space', indentWidth: 2, lineWidth: 100 },
      linter: { enabled: true, rules: { recommended: true } },
      javascript: { formatter: { quoteStyle: 'single', semicolons: 'always' } },
    },
    null,
    2,
  )}\n`;
}

function prettierConfig(): string {
  return `${JSON.stringify(
    {
      plugins: ['prettier-plugin-astro'],
      useTabs: false,
      tabWidth: 2,
      singleQuote: true,
      printWidth: 100,
      overrides: [{ files: '*.astro', options: { parser: 'astro' } }],
    },
    null,
    2,
  )}\n`;
}

function prettierIgnore(): string {
  return `node_modules/
.astro/
dist/
package-lock.json
`;
}

function gitignore(): string {
  return `# build output
dist/
.astro/
/.cache/

# dependencies
node_modules/

# env files
.env
.env.local
.env.*.local
.env.production

# logs
npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
yarn-error.log*

# astro-mate scratch (temp prompt file; stays if the runner is killed mid-run)
.astro-mate-prompt.md

# system
.DS_Store
`;
}

function robotsTxt(site: string): string {
  return `User-agent: *
Allow: /

# AI crawlers explicitly welcomed
User-agent: GPTBot
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: OAI-SearchBot
Allow: /

User-agent: Google-Extended
Allow: /

Sitemap: ${site}/sitemap-index.xml
`;
}

function seoComponent(): string {
  return `---
interface Props {
  title: string;
  description: string;
  image?: string;
  canonical?: string;
  type?: 'website' | 'article';
  noindex?: boolean;
  jsonLd?: Record<string, unknown> | Record<string, unknown>[];
}

const {
  title,
  description,
  image,
  canonical,
  type = 'website',
  noindex = false,
  jsonLd,
} = Astro.props;

const siteURL = Astro.site ?? new URL('https://example.com');
const canonicalURL = canonical ?? new URL(Astro.url.pathname, siteURL).href;
const imageURL = image ? new URL(image, siteURL).href : undefined;
---

<title>{title}</title>
<meta name="description" content={description} />
<link rel="canonical" href={canonicalURL} />
{noindex && <meta name="robots" content="noindex, nofollow" />}

<meta property="og:title" content={title} />
<meta property="og:description" content={description} />
<meta property="og:type" content={type} />
<meta property="og:url" content={canonicalURL} />
{imageURL && <meta property="og:image" content={imageURL} />}

<meta name="twitter:card" content={imageURL ? 'summary_large_image' : 'summary'} />
<meta name="twitter:title" content={title} />
<meta name="twitter:description" content={description} />
{imageURL && <meta name="twitter:image" content={imageURL} />}

{
  jsonLd && (
    <script type="application/ld+json" is:inline set:html={JSON.stringify(jsonLd)} />
  )
}
`;
}

function layout(): string {
  return `---
import '../styles/global.css';
import SEO from '../components/SEO.astro';
import { Font } from 'astro:assets';

interface Props {
  title: string;
  description: string;
  image?: string;
  canonical?: string;
  type?: 'website' | 'article';
  noindex?: boolean;
  jsonLd?: Record<string, unknown> | Record<string, unknown>[];
}

const { title, description, image, canonical, type, noindex, jsonLd } = Astro.props;

const siteURL = Astro.site ?? new URL('https://example.com');
const defaultJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: title,
  url: siteURL.href,
};
---

<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <meta name="generator" content={Astro.generator} />
    <Font cssVariable="--font-inter" />
    <SEO
      title={title}
      description={description}
      image={image}
      canonical={canonical}
      type={type}
      noindex={noindex}
      jsonLd={jsonLd ?? defaultJsonLd}
    />
  </head>
  <body class="min-h-screen bg-white font-sans text-slate-900 antialiased dark:bg-slate-950 dark:text-slate-100">
    <slot />
  </body>
</html>
`;
}

function indexPage(): string {
  return `---
import Layout from '../layouts/Layout.astro';
---

<Layout
  title="Hello from astro-mate"
  description="A starter site scaffolded by astro-mate — Astro, Tailwind, and a built-in SEO baseline."
>
  <main class="mx-auto max-w-2xl px-6 py-24">
    <h1 class="text-4xl font-bold tracking-tight">Hello from astro-mate</h1>
    <p class="mt-4 text-lg text-slate-600 dark:text-slate-400">
      Edit <code class="rounded bg-slate-100 px-1.5 py-0.5 text-sm dark:bg-slate-800">src/pages/index.astro</code>
      to begin.
    </p>
  </main>
</Layout>
`;
}

function globalCss(): string {
  return `@import "tailwindcss";

@theme {
  --font-sans: var(--font-inter), ui-sans-serif, system-ui, sans-serif;
  --font-heading: var(--font-inter), ui-sans-serif, system-ui, sans-serif;
}

@layer base {
  h1,
  h2,
  h3,
  h4,
  h5,
  h6 {
    font-family: var(--font-heading);
  }
}
`;
}

function favicon(): string {
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="24" fill="#0f172a"/><text x="64" y="82" text-anchor="middle" font-family="system-ui,sans-serif" font-size="64" font-weight="700" fill="#f8fafc">A</text></svg>
`;
}
